### PR TITLE
Added support for handling @org/package

### PR DESCRIPTION
**Pull request by dendril**
Hey everyone!

I was having problems with packages which are not named as the folder containing the code (my personal scenario are scoped packages). So instead of use the folder's name for everything, I'm using the `package.json{name}` when running `npm dist-tag`.

Do you think we could do something to handle this scenario?

Any feedback will be welcome!

### CODE REVIEW

**Comment by dendril** [comment]
Is there any chance to get some attention from the project maintainers? I want to prevent any kind of diverge from the official version :smile: 

Thanks again.

**Comment by thejameskyle** [comment]
Sorry, I'm rewriting a lot right now, this is going to fall out of date, but I'll make sure its something that we do.

**Comment by dendril** [comment]
Cool! let me know if I can give you a hand in some way.

**Comment by thejameskyle** [comment]
Going to take on this PR in the refactored codebase. Is the only thing here that lerna needs to use the `package.json#name` for more things? Do you know which places those are?

**Comment by dendril** [comment]
```
execSync("npm dist-tag rm " + pkgObject.pkgName + " prerelease");
execSync("npm dist-tag add " + pkgObject.pkgName + "@" + NEW_VERSION + " stable");
execSync("npm dist-tag add " + pkgObject.pkgName + "@" + NEW_VERSION + " latest");
```

**Comment by thejameskyle** [comment]
Alright, I'll make that happen

**Comment by dendril** [comment]
Yay! Thanks!

**Comment by thejameskyle** [comment]
Moving to: #33

**Comment by dchambers** [comment]
That's remarkably good timing! I just tried to use Lerna for the first time but found it doesn't currently work because I'm using scoped package names. Looking forward to a release containing the fix :smile:.

**Pull request closed without merging**
