### PR TITLE
Run and ls

### PR DESCRIPTION
**Pull request by thejameskyle**
Moving from #5

### CODE REVIEW

**Comment by hzoo** [comment]
Can update the readme for this one as well

**Comment by thejameskyle** [comment]
Actually, I think we should completely rewrite the README before 2.0

**Comment by hzoo** [comment]
Kk, we suddenly have a lot more commands

**Comment by hzoo** [comment]
Oh maybe `ls` could provide more info (or maybe that is a different command)? It's the same as updated except all packages

It could print like: name, last version (useful for independent mode?), if changed, last update, last tag date, etc?

**Comment by thejameskyle** [comment]
Sure, want to make a PR? Otherwise I can get to it tomorrow

**Pull request merged**
