### PR TITLE
Push version tags explicitly

### PR DESCRIPTION
**Pull request by gigabo**
Somehow `--follow-tags` doesn't always work.

https://github.com/kittens/lerna/issues/52

### CODE REVIEW

**Comment by thejameskyle** [comment]
This isn't going to work with #36, does `git push --tags`

**Comment by gigabo** [comment]
Doesn't `git push --tags` push _all_ tags?  That seems unsafe.

Would this work with #36 if `tags` were passed to `gitPushWithTags` instead of `version`?

```javascript
function gitPushWithTags(tags) {
  execSync("git push");
  execSync("git push origin " + tags.join(" "));
}
```

**Comment by thejameskyle** [comment]
That would work too, I'll merge the independent mode PR shortly.

**Comment by thejameskyle** [comment]
@gigabo could you rebase this when you get a chance?

**Comment by gigabo** [comment]
Rebased.  I'll update for compatibility with independent mode when that lands, too.  Thanks.

**Comment by thejameskyle** [comment]
Hey @gigabo, just merged #36. Want to update this? I might just grab it and fix it up to merge it this weekend if you don't have time to do it.

**Comment by gigabo** [comment]
Hi @thejameskyle, I missed this over the weekend.  I'll update this morning.

**Comment by gigabo** [comment]
Updated and [tested](https://github.com/redfin/react-server/releases/tag/v0.0.10).

**Comment by thejameskyle** [comment]
Thanks!

**Pull request merged**
