### PR TITLE
typo

### PR DESCRIPTION
**Pull request by hzoo**
`git tag` instead of `git tags`? @thejameskyle

### CODE REVIEW

**Comment by thejameskyle** [comment]
Why would this be `git tag` it's supposed to list them off?

**Comment by hzoo** [comment]
Oh I just tried `git tags` and was getting an error so was wondering if that was just me?

screen shot 2016-01-23 at 11 14 03 am

**Comment by thejameskyle** [comment]
Weird...
```
➜  lerna git:(master) ✗ git tags
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.0.5
v1.1.0
```

**Comment by hzoo** [comment]
Haha weird.. maybe different versions or alias?

**Pull request merged**
